### ISSUE TITLE
files not getting uploaded. always getting critical error while uploading files and after that node server crashes.. 

### ISSUE THREAD

**Issue by nikita2106** [cloverstudio/Spika#20]
getting this error stack trace:
TypeError: callback must be a function
    at makeCallback (evalmachine.<anonymous>:78:11)
    at Object.fs.rename (evalmachine.<anonymous>:668:14)
    at /root/myolo/myolo/Spika/web/src/server/WebAPI/FileUploadHandler.js:197:40
    at model.<anonymous> (/root/myolo/myolo/Spika/web/node_modules/mongoose/lib/document.js:1913:20)
    at next_ (/root/myolo/myolo/Spika/web/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/root/myolo/myolo/Spika/web/node_modules/hooks-fixed/hooks.js:186:18)
    at /root/myolo/myolo/Spika/web/node_modules/mongoose/lib/model.js:3361:16
    at /root/myolo/myolo/Spika/web/node_modules/mongoose/lib/model.js:228:5
    at /root/myolo/myolo/Spika/web/node_modules/mongoose/lib/model.js:135:7
    at /root/myolo/myolo/Spika/web/node_modules/mongodb/lib/collection.js:504:5
    at /root/myolo/myolo/Spika/web/node_modules/mongodb/lib/collection.js:666:5
    at /root/myolo/myolo/Spika/web/src/server/WebAPI/FileUploadHandler.js:197:40
    at model.<anonymous> (/root/myolo/myolo/Spika/web/node_modules/mongoose/lib/document.js:1913:20)
    at next_ (/root/myolo/myolo/Spika/web/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/root/myolo/myolo/Spika/web/node_modules/hooks-fixed/hooks.js:186:18)
    at /root/myolo/myolo/Spika/web/node_modules/mongoose/lib/model.js:3361:16
    at /root/myolo/myolo/Spika/web/node_modules/mongoose/lib/model.js:228:5
    at /root/myolo/myolo/Spika/web/node_modules/mongoose/lib/model.js:135:7

**Comment by nikita2106** [comment]
getting the following error now:

Error: Command failed: convert C:\Users\Nikita\AppData\Local\Temp\upload_10e8bd3937af740ba1635dc1d64968a7 -auto-orient -gravity Center -interpolate bicubic -strip -thumbnail 256x -crop 256x256+0+0 public/uploads/579b0e9bd6d039b846f2daf1_thumb.jpg
convert: unrecognized interpolate method `bicubic' @ error/convert.c/ConvertImageCommand/1907

**Comment by NeoTim** [comment]
@nikita2106  how to solve?
