### ISSUE TITLE
Error while uploading images to the server.

### ISSUE THREAD

**Issue by shelan** [cloverstudio/Spika#32]
While uploading images using the webclient i am getting following error.

OS : Red Hat Enterprise Linux Server release 7.3 (Maipo)
node : 6.9.1 (LTS)

0|main     | TypeError: "callback" argument must be a function
0|main     |     at makeCallback (fs.js:119:11)
0|main     |     at Object.fs.rename (fs.js:796:14)
0|main     |     at /home/ec2-user/Spika/web/src/server/WebAPI/FileUploadHandler.js:197:40
0|main     |     at /home/ec2-user/Spika/web/node_modules/mongoose/lib/model.js:3381:16
0|main     |     at /home/ec2-user/Spika/web/node_modules/mongoose/lib/document.js:1979:18
0|main     |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
0|main     |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by beeka5** [comment]
In my case change code from fs.rename(destPathTmp, destPath,null); to fs.rename(destPathTmp, destPath, function(){return;}); worked fine.

**Comment by shelan** [comment]
@beeka5 thanks for the prompt reply. Yes you are correct and I used sync renameAsnc and it worked too. preparing a PR with a proper callback function. Because  if we use async fs.rename, logic is incorrect as it executes 

```
result.thumbModel = thumbModel;

done(err, result);
```

irrespective of the results.

will share the PR soon.
