### ISSUE TITLE
Error while running the server

### ISSUE THREAD

**Issue by azhicodan** [cloverstudio/Spika#40]
I get the following error when I run the main js file. Can anyone help me on this?
`node src/server/main.js`

Error in Terminal
```
Connecting mongoDB mongodb://localhost/simplemessenger
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Object.<anonymous> (/home/ratish/Spika/web/src/server/main.js:18:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by azhicodan** [comment]
Found the problem. Already an issue reported with same problem. 
https://github.com/cloverstudio/Spika/issues/9
