### ISSUE TITLE
Cannot find module 'jsdoc/util/doop'

### ISSUE THREAD

**Issue by devopsberlin** [cloverstudio/Spika#53]
Hi
I've followed the instructions `https://github.com/cloverstudio/Spika/tree/master/web/src/server` and I'm getting the below error:

	gulp build-dist
	Wed, 21 Jun 2017 10:45:34 GMT uncaughtException: Cannot find module 'jsdoc/util/doop'
	Error: Cannot find module 'jsdoc/util/doop'
		at Function.Module._resolveFilename (module.js:325:15)
		at Function.Module._load (module.js:276:25)
		at Module.require (module.js:353:17)
		at require (internal/module.js:12:17)
		at Object.<anonymous> (/opt/Spika/web/node_modules/gulp-jsdoc/node_modules/jsdoc/lib/jsdoc/borrow.js:9:12)
		at Module._compile (module.js:409:26)
		at Object.Module._extensions..js (module.js:416:10)
		at Module.load (module.js:343:32)
		at Function.Module._load (module.js:300:12)
		at Module.require (module.js:353:17)
		at require (internal/module.js:12:17)

```
$ lsb_release -r
Release:        14.04

$ node -v
v4.8.3

$ npm -v
2.14.22.15.11

$ /usr/bin/node -v
v4.8.3

$ /usr/bin/nodejs -v
v4.8.3

```

```
cat src/server/init.js

(function(global) {
    "use strict;"

    // Class ------------------------------------------------
    var Config = {};

    Config.host = "x.x.x.x";
    Config.port = 80;
    Config.urlPrefix = '/spika';
    Config.socketNameSpace = '/spika';

    Config.imageDownloadURL = "http://" + Config.host + "/:" + Config.port + Config.urlPrefix + "/media/images/";
    Config.noavatarImg = "http://" + Config.host + ":" + Config.port + Config.urlPrefix + "/img/noavatar.png";

    Config.chatDatabaseUrl = "mongodb://localhost/simplemessenger";
    Config.dbCollectionPrefix = "spika_";

    Config.uploadDir = 'public/uploads/';
    Config.sendAttendanceMessage = true;

    Config.stickerBaseURL = 'http://spika.chat';
    Config.stickerAPI = Config.stickerBaseURL + '/api/v2/stickers/56e005b1695213295419f5df';

    Config.apiBaseUrl = "http://localhost:8080/spika/v1";
    Config.socketUrl = "http://localhost:8080/spika";

    // Exports ----------------------------------------------
    module["exports"] = Config;

})((this || 0).self || global);
```

Can you please suggest?
Thanks

**Comment by federicosan** [comment]
I am having this error too afte editing lang/language.js

**Comment by Kwangjin-Lee** [comment]
Hi, @devopsberlin 
I have same error. Did you solve this error?

**Comment by yvolkan** [comment]
Edit web/gulpfile.js and disable jsdoc library.

```
//jsdoc = require("gulp-jsdoc");

//var JSDocTemplate = {
//      path: "ink-docstrap",
//    systemName: "Spika Web Client",
//    theme: "cosmo",
//    linenums: true
//};

//var JSDocOptions = {
//    outputSourceFiles: true
//};

//gulp.task("jsdoc", function() {
//      gulp.src(["./src/client/**/*.js", "README.md"])
//              .pipe(jsdoc.parser(infos))
//              .pipe(jsdoc.generator("./doc/WebClient", JSDocTemplate, JSDocOptions))
//});
```
