### ISSUE TITLE
Error Starting

### ISSUE THREAD

**Issue by tinyhostingltd** [cloverstudio/Spika#9]
Followed the instructions and then just get this when trying to start

root@chat:~/Spika/web# node src/server/main.js
Connecting mongoDB mongodb://localhost/simplemessenger

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Object.<anonymous> (/root/Spika/web/src/server/main.js:18:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by blwright** [comment]
I had the same issue when running apache on the same host on the same port (80).  I changed the port number in the init.js files and the server started fine.

**Comment by satheesht** [comment]
@blwright Exactly! Worked.

**Comment by jsmit6** [comment]
Unless your service is running as root or has the required RBAC privilege, you shouldn't use a privileged port. By default all ports from 1 to 1024 are privileged. This means that the default port of 80 either needs to be changed or your permissions need to be elevated by using sudo.
